### ISSUE TITLE
Apache Linkis Graduation Tasks

### ISSUE THREAD

**Issue by casionone** [apache/linkis#4051]
The ASF board has approved a resolution to graduate Linkis into a full top level project. Thanks to everyone for your help to get to this point.

To transition from the Apache Incubator to a new TLP, there's a few action items we need to do to complete the transition. These are identified by https://incubator.apache.org/guides/transferring.html#life_after_graduation.

## Task list

- Update Incubator status records
   - [ ] Update the incubator status file (in svn) 
   - [ ] Update podling status page 
- Source repo changes
   - [ ] Git repos will be renamed to drop the "incubator-" prefix, notify developers to change their remote. https://issues.apache.org/jira/browse/INFRA-24031
   - [ ]   SVN Repos —— moved from the incubator to new directory.  https://issues.apache.org/jira/browse/INFRA-24031
   - [ ] Post announcement to dev list telling everyone the repo is about to be moved
   - [ ] Post an announcement containing instructions for developers describing how to change their git remotes.
   - [ ] Update website, wikis, pom.xml, and other resources to point to the new repository location 
   - [ ] Remove DISCLAIMER from git repo
   - [ ] Remove MATURITY.md from git repo
 
- Websites
   - [ ] Remove incubating/podding related resources from the website. https://github.com/apache/incubator-linkis-website/pull/631
   - [ ] update documentation of [how to release](https://linkis.apache.org/community/how-to-release)
